server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  rate-limiter:
    configs:
      default:
        limit-for-period: 2
        limit-refresh-period: 30s
    instances:
      default:
        baseConfig: default
  retry:
    instances:
      default:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: false
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: Admin1!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    url: jdbc:mysql://localhost:3306
    schemas: book_service
    user: root
    password: Admin1!
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
springdoc:
  show-actuator: true
  api-docs:
    path: book-service/v3/api-docs